name: opencv_ffi
description: An FFI implementation of the C++ OpenCV library in Dart, with video I/O, image encodings and processing, and some GUI elements.
version: 1.0.0
repository: https://github.com/Levi-Lesches/OpenCV-FFI

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2

dev_dependencies:
  ffigen: ^9.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1

topics: 
  - ffi
  - opencv
  - video
  - image
  - camera
